// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDuAnDauTu.Ser.Infrastructure;

#nullable disable

namespace QuanLyDuAnDauTu.Ser.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230428073241_addTableDuAn_2")]
    partial class addTableDuAn_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDuAnDauTu.Ser.Domain.Entities.SqlServerCCKL.Danhmuc.MasPhuongXa", b =>
                {
                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedUser_ID");

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastUpdDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LastUpdUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdUser_ID");

                    b.Property<string>("MaPhuongXa")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PhuongXaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhuongXa_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhuongXaId"));

                    b.Property<int?>("QuanHuyenId")
                        .HasColumnType("int")
                        .HasColumnName("QuanHuyen_ID");

                    b.Property<string>("TenPhuongXa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("Mas_PhuongXa", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAnDauTu.Ser.Domain.Entities.SqlServerCCKL.Danhmuc.MasQuanHuyen", b =>
                {
                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedUser_ID");

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastUpdDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LastUpdUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdUser_ID");

                    b.Property<string>("MaQuanHuyen")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuanHuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuanHuyen_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuanHuyenId"));

                    b.Property<string>("TenQuanHuyen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("TinhThanhId")
                        .HasColumnType("tinyint")
                        .HasColumnName("TinhThanh_ID");

                    b.ToTable("Mas_QuanHuyen", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAnDauTu.Ser.Domain.Entities.SqlServerCCKL.Danhmuc.MasTinhThanh", b =>
                {
                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedUser_ID");

                    b.Property<string>("IsDeleted")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastUpdDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LastUpdUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastUpdUser_ID");

                    b.Property<string>("MaTinhThanh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenTinhThanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("TinhThanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("TinhThanh_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("TinhThanhId"));

                    b.ToTable("Mas_TinhThanh", (string)null);
                });

            modelBuilder.Entity("QuanLyDuAnDauTu.Ser.Domain.Entities.SqlServerCCKL.Duan.DuAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ChiPhiDuPhong")
                        .HasColumnType("bigint");

                    b.Property<long>("ChiPhiKhac")
                        .HasColumnType("bigint");

                    b.Property<long>("ChiPhiQuanLyDuAn")
                        .HasColumnType("bigint");

                    b.Property<long>("ChiPhiThietBi")
                        .HasColumnType("bigint");

                    b.Property<long>("ChiPhiTuVan")
                        .HasColumnType("bigint");

                    b.Property<long>("ChiPhiXayLap")
                        .HasColumnType("bigint");

                    b.Property<int>("ChuDauTuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HinhThucQuanLyDuAnID")
                        .HasColumnType("int");

                    b.Property<string>("MaDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucTieuDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguonVonID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungVaQuyMo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhanLoaiDuAnID")
                        .HasColumnType("int");

                    b.Property<int>("PhanNhomDuAnID")
                        .HasColumnType("int");

                    b.Property<int>("PhuongXaID")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenID")
                        .HasColumnType("int");

                    b.Property<int>("QuyTrinhQuanLyDauTuID")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThucHienDenNgay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThucHienTuNgay")
                        .HasColumnType("datetime2");

                    b.Property<int>("TinhChatDuAnID")
                        .HasColumnType("int");

                    b.Property<int>("TinhThanhID")
                        .HasColumnType("int");

                    b.Property<string>("TongMucDauTu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_DUAN_DuAnId");

                    b.ToTable("DU_AN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
